#requires -RunAsAdministrator
<#
.SYNOPSIS
  Hardens a dedicated Windows iVMS kiosk by disabling services not required
  for the kiosk role.

.DESCRIPTION
  Designed for a dedicated kiosk whose primary functions are:
    - Boot Windows
    - Auto-logon as Kiosk
    - Launch iVMS-4200
    - Maintain Ethernet/IP connectivity
    - Run Scheduled Tasks
    - Permit RDP administration
    - Reboot on schedule

  This script:
    1. Backs up current service startup modes.
    2. Creates a generated rollback script.
    3. Disables a conservative set of nonessential kiosk services.
    4. Disables Windows Update-related services because patching is manual.
    5. Leaves core networking, RPC, WMI, Event Log, Task Scheduler,
       Windows Firewall/BFE, RDP, audio, certificates, Plug and Play,
       DHCP/DNS, and time services intact.

  Review the OPTIONAL switches below before running.

.NOTES
  Run from an elevated PowerShell session.
#>

[CmdletBinding()]
param(
    # Enable these only when the kiosk does not use the corresponding feature.
    [switch]$DisablePrinting,
    [switch]$DisableBluetooth,
    [switch]$DisableLocationSensors,
    [switch]$DisableUPnP,
    [switch]$DisableWindowsUpdate = $true
)

$ErrorActionPreference = 'Continue'

# ---------------------------------------------------------------------------
# Configuration / logging
# ---------------------------------------------------------------------------

$Root = 'C:\ProgramData\KioskHardening'
$Stamp = Get-Date -Format 'yyyyMMdd-HHmmss'
$BackupCsv = Join-Path $Root "Services-Before-$Stamp.csv"
$RollbackPs1 = Join-Path $Root "Restore-Services-$Stamp.ps1"
$LogFile = Join-Path $Root "Kiosk-Hardening-$Stamp.log"

New-Item -Path $Root -ItemType Directory -Force | Out-Null
Start-Transcript -Path $LogFile -Force

Write-Host "`n=== iVMS Kiosk Service Hardening ===" -ForegroundColor Cyan
Write-Host "Backup:   $BackupCsv"
Write-Host "Rollback: $RollbackPs1"
Write-Host "Log:      $LogFile`n"

# ---------------------------------------------------------------------------
# Backup current service state
# Use Win32_Service because StartMode maps cleanly to Automatic/Manual/Disabled.
# ---------------------------------------------------------------------------

$Before = Get-CimInstance Win32_Service |
    Select-Object Name, DisplayName, State, StartMode, StartName, PathName

$Before | Export-Csv -Path $BackupCsv -NoTypeInformation -Encoding UTF8

# Generate rollback script from the current machine state.
$rollbackHeader = @"
#requires -RunAsAdministrator
# Generated by Kiosk-Hardening.ps1 on $(Get-Date)
# Restores service startup types captured before kiosk hardening.

`$ErrorActionPreference = 'Continue'

function Restore-StartupType {
    param(
        [string]`$Name,
        [string]`$StartMode
    )

    if (-not (Get-Service -Name `$Name -ErrorAction SilentlyContinue)) {
        return
    }

    switch (`$StartMode) {
        'Auto'     { sc.exe config "`$Name" start= auto   | Out-Null }
        'Manual'   { sc.exe config "`$Name" start= demand | Out-Null }
        'Disabled' { sc.exe config "`$Name" start= disabled | Out-Null }
    }
}
"@

Set-Content -Path $RollbackPs1 -Value $rollbackHeader -Encoding UTF8

foreach ($svc in $Before) {
    $escapedName = $svc.Name.Replace("'", "''")
    Add-Content -Path $RollbackPs1 -Value "Restore-StartupType -Name '$escapedName' -StartMode '$($svc.StartMode)'"
}

Add-Content -Path $RollbackPs1 -Value @'

Write-Host "Startup types restored. Reboot Windows to fully return to the captured service configuration."
'@

# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------

function Disable-KioskService {
    param(
        [Parameter(Mandatory)]
        [string]$Name,

        [string]$Reason = ''
    )

    $svc = Get-Service -Name $Name -ErrorAction SilentlyContinue

    if (-not $svc) {
        Write-Host "[SKIP] $Name - not installed"
        return
    }

    Write-Host "[DISABLE] $Name - $Reason"

    if ($svc.Status -ne 'Stopped') {
        try {
            Stop-Service -Name $Name -Force -ErrorAction Stop
        }
        catch {
            Write-Warning "Could not stop $Name now: $($_.Exception.Message)"
        }
    }

    # sc.exe is used because several Windows services behave more consistently
    # with SCM than Set-Service when modifying startup configuration.
    $result = & sc.exe config "$Name" start= disabled 2>&1

    if ($LASTEXITCODE -ne 0) {
        Write-Warning "Could not set $Name to Disabled: $($result -join ' ')"
    }
}

# ---------------------------------------------------------------------------
# BASELINE: services that are normally unnecessary on a fixed iVMS kiosk
# ---------------------------------------------------------------------------

$BaselineServices = [ordered]@{
    'DiagTrack'       = 'Connected User Experiences / telemetry'
    'MapsBroker'      = 'Offline downloaded maps'
    'WSearch'         = 'Windows Search indexing'
    'SysMain'         = 'SysMain prefetching; unnecessary for fixed kiosk workload'
    'TrkWks'          = 'Distributed Link Tracking Client'
    'WMPNetworkSvc'   = 'Windows Media Player network sharing'
    'RetailDemo'      = 'Retail Demo'
    'PhoneSvc'        = 'Phone integration'
    'WalletService'   = 'Windows Wallet'
    'wisvc'           = 'Windows Insider'
    'XblAuthManager'  = 'Xbox Live authentication'
    'XblGameSave'     = 'Xbox Live game saves'
    'XboxGipSvc'      = 'Xbox accessories'
    'XboxNetApiSvc'   = 'Xbox networking'
    'Fax'             = 'Fax'
    'icssvc'          = 'Mobile Hotspot'
    'SharedAccess'    = 'Internet Connection Sharing'
    'PushToInstall'   = 'Remote Microsoft Store Push-To-Install'
    'dmwappushservice'= 'WAP push routing / device-management messaging'
    'WerSvc'          = 'Windows Error Reporting'
}

foreach ($entry in $BaselineServices.GetEnumerator()) {
    Disable-KioskService -Name $entry.Key -Reason $entry.Value
}

# ---------------------------------------------------------------------------
# WINDOWS UPDATE
#
# This intentionally prevents automatic Windows servicing.
# To patch manually later, run the generated rollback script or re-enable:
#   BITS      = demand
#   wuauserv  = demand
#   UsoSvc    = demand/auto depending Windows build
#   DoSvc     = demand/auto depending Windows build
# ---------------------------------------------------------------------------

if ($DisableWindowsUpdate) {
    Write-Host "`n--- Disabling Windows Update services ---" -ForegroundColor Yellow

    $UpdateServices = [ordered]@{
        'wuauserv' = 'Windows Update'
        'UsoSvc'   = 'Update Orchestrator'
        'BITS'     = 'Background Intelligent Transfer Service'
        'DoSvc'    = 'Delivery Optimization'
    }

    foreach ($entry in $UpdateServices.GetEnumerator()) {
        Disable-KioskService -Name $entry.Key -Reason $entry.Value
    }

    # Disable common Windows Update scheduled tasks when Windows permits it.
    # Some tasks are protected and may return Access Denied; this is logged
    # and is not fatal.
    $TaskPaths = @(
        '\Microsoft\Windows\WindowsUpdate\',
        '\Microsoft\Windows\UpdateOrchestrator\'
    )

    foreach ($path in $TaskPaths) {
        try {
            Get-ScheduledTask -TaskPath $path -ErrorAction Stop |
                ForEach-Object {
                    try {
                        Disable-ScheduledTask -InputObject $_ -ErrorAction Stop | Out-Null
                        Write-Host "[TASK DISABLED] $($_.TaskPath)$($_.TaskName)"
                    }
                    catch {
                        Write-Warning "Could not disable task $($_.TaskPath)$($_.TaskName): $($_.Exception.Message)"
                    }
                }
        }
        catch {
            Write-Host "[SKIP] Scheduled task path not present: $path"
        }
    }
}

# ---------------------------------------------------------------------------
# OPTIONAL FEATURE GROUPS
# ---------------------------------------------------------------------------

if ($DisablePrinting) {
    Write-Host "`n--- Disabling printing ---" -ForegroundColor Yellow
    @(
        'Spooler',
        'PrintNotify',
        'PrintDeviceConfigurationService',
        'PrintScanBrokerService'
    ) | ForEach-Object {
        Disable-KioskService -Name $_ -Reason 'Printing not used on kiosk'
    }
}

if ($DisableBluetooth) {
    Write-Host "`n--- Disabling Bluetooth ---" -ForegroundColor Yellow
    @(
        'bthserv',
        'BthAvctpSvc',
        'BTAGService'
    ) | ForEach-Object {
        Disable-KioskService -Name $_ -Reason 'Bluetooth not used on kiosk'
    }

    # Per-user BluetoothUserService_* instances are intentionally left alone.
    # Disabling the base Bluetooth services prevents normal Bluetooth operation
    # without modifying dynamic per-user service templates.
}

if ($DisableLocationSensors) {
    Write-Host "`n--- Disabling location / sensor services ---" -ForegroundColor Yellow
    @(
        'lfsvc',
        'SensorDataService',
        'SensorService',
        'SensrSvc'
    ) | ForEach-Object {
        Disable-KioskService -Name $_ -Reason 'Location/sensors not used on kiosk'
    }
}

if ($DisableUPnP) {
    Write-Host "`n--- Disabling SSDP / UPnP ---" -ForegroundColor Yellow
    @(
        'SSDPSRV',
        'upnphost'
    ) | ForEach-Object {
        Disable-KioskService -Name $_ -Reason 'UPnP discovery not required'
    }
}

# ---------------------------------------------------------------------------
# Explicit keep list -- informational guardrail
# ---------------------------------------------------------------------------

$KeepServices = @(
    'Schedule',                 # Task Scheduler
    'EventLog',                 # Windows Event Log
    'RpcSs',                    # RPC
    'RpcEptMapper',             # RPC Endpoint Mapper
    'DcomLaunch',               # DCOM
    'BFE',                      # Base Filtering Engine
    'mpssvc',                   # Windows Defender Firewall
    'Winmgmt',                  # WMI
    'PlugPlay',                 # Plug and Play
    'Power',                    # Power
    'ProfSvc',                  # User Profile Service
    'Dhcp',                     # DHCP Client
    'Dnscache',                 # DNS Client
    'NlaSvc',                   # Network Location Awareness
    'nsi',                      # Network Store Interface
    'LanmanWorkstation',        # Workstation
    'CryptSvc',                 # Cryptographic Services
    'W32Time',                  # Windows Time
    'TermService',              # Remote Desktop Services
    'SessionEnv',               # RDP Configuration
    'UmRdpService',             # RDP UserMode Port Redirector
    'AudioEndpointBuilder',     # iVMS may use audio
    'Audiosrv'                  # Windows Audio
)

Write-Host "`n--- Protected KEEP list (not modified) ---" -ForegroundColor Green
$KeepServices | ForEach-Object {
    $svc = Get-Service -Name $_ -ErrorAction SilentlyContinue
    if ($svc) {
        Write-Host ("[KEEP] {0,-25} {1,-10} {2}" -f $_, $svc.Status, $svc.DisplayName)
    }
}

# ---------------------------------------------------------------------------
# Result report
# ---------------------------------------------------------------------------

$ResultCsv = Join-Path $Root "Services-After-$Stamp.csv"

Get-CimInstance Win32_Service |
    Select-Object Name, DisplayName, State, StartMode |
    Export-Csv -Path $ResultCsv -NoTypeInformation -Encoding UTF8

Write-Host "`n=== Complete ===" -ForegroundColor Cyan
Write-Host "No reboot was performed."
Write-Host "After-state: $ResultCsv"
Write-Host "Rollback:    $RollbackPs1"
Write-Host ""
Write-Host "Recommended validation before the next scheduled reboot:"
Write-Host "  1. iVMS remains open and camera streams are live."
Write-Host "  2. Ethernet/network access works."
Write-Host "  3. RDP still works."
Write-Host "  4. Scheduled tasks remain present:"
Write-Host '       schtasks /Query /TN "Kiosk\Launch iVMS" /V /FO LIST'
Write-Host '       schtasks /Query /TN "Kiosk\Daily Reboot" /V /FO LIST'
Write-Host ""
Write-Host "After the 06:30 reboot, verify auto-logon and iVMS startup."

Stop-Transcript
